train:
  log_clearml: True
  epochs: 50
  task_name: convnext
  model_save_path: convnext
  optimizer_name: radam
dataloader:
  augmentations_intensity: 0.8
  data_dir: /home/alenaastrakhantseva/PycharmProjects/Captcha/data
  train_path: processed/synthetic/train_set.csv
  eval_path: processed/synthetic/eval_set.csv
  test_path: processed/test_set.csv
  test_size: 0
  batch_size: 16
net:
  resume_weights: ""
  freeze_grads: False
  pretrained: True
  model_name: convnext
scheduler:
  scheduler: True
  t0: 1
  t_mult: 2