train:
  log_clearml: True
  epochs: 50
  task_name: rexnet_2
  model_save_path: rexnet_2
  optimizer_name: radam
  scheduler: True
dataloader:
  augmentations_intensity: 0.8
  data_dir: /home/alenaastrakhantseva/PycharmProjects/Captcha/data
  train_path: processed/synthetic/train_set.csv
  eval_path: processed/synthetic/eval_set.csv
  test_path: processed/test_set.csv
  test_size: 0
  batch_size: 32
net:
  continue_weights: ""
  freeze_grads: False
  pretrained: True
  model_name: rexnet-100