train:
  log_clearml: True
  epochs: 100
  task_name: synthetic_more_aug
  train_path: processed/synthetic/train_set.csv
  eval_path: processed/synthetic/eval_set.csv
  augmentations_intensity: 0.8
  model_save_path: synthetic_more_aug
  test_size: 0
  batch_size: 32
net:
  freeze_grads: False